const defaultPlayers=['Ariel','Benjamin','Emerson','Hudson','Thomas','Magnolia','Dylan','Everett','Oaklee','Matthew'];
const segments=[
 {title:'Team Huddle + Safety',range:'2:00–2:04',mins:4,desc:'Welcome, safety rules, Fireflies cheer.',cues:['No swinging until a coach says go.','When Coach says FREEZE, everybody freezes.','Hustle between drills.','Fireflies on 3!']},
 {title:'Baseball Warm-Up',range:'2:04–2:10',mins:6,desc:'Movement, bases, easy throwing.',cues:['Jog all four bases.','High knees + side shuffle.','Home → first at game speed.','Easy partner throws.']},
 {title:'Station Rotation',range:'2:10–2:31',mins:21,desc:'3 groups rotate through hitting, grounders, throwing/bases.',cues:['3 groups: 4 / 3 / 3.','7 minutes per station.','Coaches stay at stations; players rotate.','Keep lines moving.'],round:true},
 {title:'Water + Quick Reset',range:'2:31–2:33',mins:2,desc:'Fast drink and reset.',cues:['Water only.','Get back to the infield quickly.']},
 {title:'Fireflies Team Defense',range:'2:33–2:41',mins:8,desc:'Field the ball and get it toward first.',cues:['Coach rolls or hits easy balls.','Rotate first base every 2–3 balls.','Team goal: 10 good plays.','Praise effort loudly.']},
 {title:'Home Run Relay',range:'2:41–2:44',mins:3,desc:'Fast, fun base-running finish.',cues:['Everyone runs the bases.','Touch every bag.','Cheer for teammates.']},
 {title:'Huddle + Fireflies Cheer',range:'2:44–2:45',mins:1,desc:'One lesson, one compliment, team cheer.',cues:['Ask: What base do we run to first?','Recognize hustle and listening.','1, 2, 3 — FIREFLIES!']}
];
const stationDefs=[
 {name:'Hitting',coach:0,cue:'Tee first. Feet set • eyes on ball • swing through • drop bat safely • run through first.'},
 {name:'Ground Balls',coach:1,cue:'Feet apart • butt down • glove to dirt • two hands • field → stand → throw.'},
 {name:'Throwing + Bases',coach:2,cue:'Step toward target • short throws • name the bases • touch every bag • run through first.'}
];
let state={idx:0,overall:45*60,segment:segments[0].mins*60,running:false,round:0};
let timer=null;
let roster=JSON.parse(localStorage.getItem('firefliesRoster')||'null')||defaultPlayers.slice();
let coaches=JSON.parse(localStorage.getItem('firefliesCoaches')||'null')||['Head Coach','Coach 2','Coach 3'];
let groupOrder=JSON.parse(localStorage.getItem('firefliesGroups')||'null')||roster.slice();
const $=id=>document.getElementById(id);
const fmt=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)}
function groups(){const clean=groupOrder.filter(Boolean);return [clean.slice(0,4),clean.slice(4,7),clean.slice(7,10)];}
function stationFor(groupIdx,round){return (groupIdx+round)%3;}
function renderNow(){const s=segments[state.idx];$('overall').textContent=fmt(state.overall);$('segmentTime').textContent=fmt(state.segment);$('segmentLabel').textContent=`Segment ${state.idx+1} of ${segments.length}`;$('segmentTitle').textContent=s.title;$('segmentRange').textContent=s.range;$('cueList').innerHTML=s.cues.map(x=>`<li>${x}</li>`).join('');$('statusText').textContent=state.running?'RUNNING':'READY';$('startBtn').textContent=state.running?'PAUSE':(state.overall===45*60?'START':'RESUME');$('progressBar').style.width=`${Math.min(100,Math.max(0,(45*60-state.overall)/(45*60)*100))}%`;$('roundBadge').style.display=s.round?'flex':'none';$('roundBadge').textContent=`ROUND ${state.round+1}`;const n=segments[Math.min(state.idx+1,segments.length-1)];$('upNextRange').textContent=n.range;$('upNextTitle').textContent=n.title;$('upNextDesc').textContent=n.desc;$('upNextTime').textContent=state.idx===segments.length-1?'DONE':`${n.mins} min`;}
function renderTimeline(){$('timeline').innerHTML=segments.map((s,i)=>`<div class="step ${i===state.idx?'current':''}"><div class="time">${s.range}</div><div><strong>${s.title}</strong><small>${s.desc}</small></div><div class="mins">${s.mins} MIN</div></div>`).join('')}
function renderRoster(){const r=$('rosterInputs');r.innerHTML='';for(let i=0;i<10;i++){const inp=document.createElement('input');inp.value=roster[i]||'';inp.placeholder=`Player ${i+1}`;inp.dataset.i=i;r.appendChild(inp)}coaches.forEach((c,i)=>$(`coach${i}`).value=c);renderGroups()}
function renderGroups(){const gs=groups();$('groupPreview').innerHTML=gs.map((g,i)=>`<div class="station"><div class="shead"><div><div class="num">GROUP ${String.fromCharCode(65+i)}</div><h3>${g.length} players</h3></div></div><div class="players">${g.map(p=>`<span class="chip">${p}</span>`).join('')}</div></div>`).join('')}
function renderStations(){const gs=groups();$('stationGrid').innerHTML=gs.map((g,gi)=>{const si=stationFor(gi,state.round),sd=stationDefs[si];return `<div class="station"><div class="shead"><div><div class="num">GROUP ${String.fromCharCode(65+gi)}</div><h3>${sd.name}</h3></div><div class="coach">${coaches[sd.coach]||`Coach ${sd.coach+1}`}</div></div><div class="players">${g.map(p=>`<span class="chip">${p}</span>`).join('')}</div></div>`}).join('');$('stationCues').innerHTML=stationDefs.map((s,i)=>`<div class="stationcue"><strong>${s.name} — ${coaches[s.coach]||`Coach ${i+1}`}</strong>${s.cue}</div>`).join('');document.querySelectorAll('.roundswitch button').forEach((b,i)=>b.classList.toggle('active',i===state.round))}
function renderAll(){renderNow();renderTimeline();renderStations();}
function next(){if(state.idx<segments.length-1){state.idx++;state.segment=segments[state.idx].mins*60;state.round=0}else{state.running=false;clearInterval(timer);timer=null}renderAll()}
function prev(){if(state.idx>0){state.idx--;state.segment=segments[state.idx].mins*60;state.round=0}renderAll()}
function tick(){if(!state.running)return;if(state.overall>0)state.overall--;if(state.segment>0)state.segment--;if(segments[state.idx].round){const elapsed=segments[state.idx].mins*60-state.segment;state.round=Math.min(2,Math.floor(elapsed/(7*60)));}if(state.segment<=0&&state.overall>0)next();if(state.overall<=0){state.running=false;clearInterval(timer);timer=null}renderAll()}
$('startBtn').addEventListener('click',()=>{state.running=!state.running;if(state.running&&!timer)timer=setInterval(tick,1000);renderAll()});$('nextBtn').addEventListener('click',next);$('prevBtn').addEventListener('click',prev);$('plusBtn').addEventListener('click',()=>{state.segment+=60;state.overall=Math.min(45*60,state.overall+60);renderAll()});$('minusBtn').addEventListener('click',()=>{state.segment=Math.max(0,state.segment-60);state.overall=Math.max(0,state.overall-60);renderAll()});$('resetBtn').addEventListener('click',()=>{if(timer)clearInterval(timer);timer=null;state={idx:0,overall:45*60,segment:segments[0].mins*60,running:false,round:0};renderAll();toast('Practice reset')});
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`view-${btn.dataset.view}`).classList.add('active')}));document.querySelectorAll('.roundswitch button').forEach(btn=>btn.addEventListener('click',()=>{state.round=Number(btn.dataset.round);renderStations()}));
$('saveRoster').addEventListener('click',()=>{roster=[...document.querySelectorAll('#rosterInputs input')].map(x=>x.value.trim()).filter(Boolean);while(roster.length<10)roster.push('');coaches=[0,1,2].map(i=>$(`coach${i}`).value.trim()||`Coach ${i+1}`);groupOrder=roster.filter(Boolean);localStorage.setItem('firefliesRoster',JSON.stringify(roster));localStorage.setItem('firefliesCoaches',JSON.stringify(coaches));localStorage.setItem('firefliesGroups',JSON.stringify(groupOrder));renderGroups();renderStations();toast('Roster saved')});
$('shuffleRoster').addEventListener('click',()=>{groupOrder=roster.filter(Boolean).slice();for(let i=groupOrder.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[groupOrder[i],groupOrder[j]]=[groupOrder[j],groupOrder[i]]}localStorage.setItem('firefliesGroups',JSON.stringify(groupOrder));renderGroups();renderStations();toast('Groups shuffled')});
renderRoster();renderAll();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));